version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: bisso
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: bisso
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://bisso:pass@mongo:27017/
