version: 3.9;
services:
  express_shop_db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_USER: bisso
      MARIADB_PASSWORD: pass
      MARIADB_DATABASE: express_shop_DB
    ports:
      - 3308:3306
    volumes:
      - ./db_backup:/docker-entrypoint-initdb.d
      # - ./db_backup:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_USER=bisso
      - PMA_PASSWORD=pass
      - PMA_HOST=express_shop_db
